///USUARIOS
export const ALTA_USUARIO ="ALTA_USUARIO";
export const ALTA_USUARIO_MASIVA ="ALTA_USUARIO_MASIVA";
export const CONSULTAR_USUARIOS ="CONSULTAR_USUARIOS";
export const UPDATE_USUARIO= "UPDATE_USUARIO";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const FILTRAR_USUARIOS = "FILTRAR_USUARIOS";
///FILTRAR_USUARIOS
/////PREGUNTAS

export const ALTA_PREGUNTA= "ALTA_PREGUNTA";
export const ALTA_PREGUNTAS_MASIVA ="ALTA_PREGUNTAS_MASIVA";
export const CONSULTAR_PREGUNTAS ="CONSULTAR_PREGUNTAS";
export const CONSULTAR_PREGUNTA = "CONSULTAR_PREGUNTA";
export const CONSULTAR_PREGUNTAS_TIPO ="CONSULTAR_PREGUNTAS_TIPO";
export const UPDATE_PREGUNTAS= "UPDATE_PREGUNTAS";
export const DELETE_PREGUNTAS = "DELETE_PREGUNTAS";
export const ERROR_PREGUNTA="ERROR_PREGUNTA";
export const EXITO_PREGUNTA="EXITO_PREGUNTA";
export const NULL_MENSAJE="NULL_MENSAJE";

////TIPOS
export const ALTA_TIPO="ALTA_TIPO"
export const CONSULTAR_TIPO ="CONSULTAR_TIPO";
export const UPDATE_TIPO= "UPDATE_TIPO";
export const DELETE_TIPO = "DELETE_TIPO";
export const SETEARANULL  = "SETEARANULL" ;

////EXAMENES
export const ALTA_EXAMEN="ALTA_EXAMEN";
export const CONSULTAR_EXAMEN ="CONSULTAR_EXAMEN";
export const UPDATE_EXAMEN= "UPDATE_EXAMEN";
export const DELETE_EXAMEN = "DELETE_EXAMEN";
export const ERROR_EXAMEN= "ERROR_EXAMEN";
export const EXITO_EXAMEN= "EXITO_EXAMEN";
export const NULL_EXAMEN= "NULL_EXAMEN";
export const CONSULTAR_TIPOS= "CONSULTAR_TIPOS";
export const CONSULTAR_EXAMENES= "CONSULTAR_EXAMENES";

//CONSULTAR_TIPOS
//export const SETEARANULL  = "SETEARANULL" ;

